# -*- coding: utf-8 -*-
"""Iris classification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O4h93knjWkoOUTyDGTFbUGhGFRKh509f

#### 종속변수가 범주형일때 분류 모델을 만드는 방법
"""

import pandas as pd
import tensorflow as tf

iris_dir='https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
iris=pd.read_csv(iris_dir)
display(iris.head())

#원핫 인코딩
encoding=pd.get_dummies(iris)
display(encoding)

#독립변수, 종속변수
a=encoding[['꽃잎길이','꽃잎폭','꽃받침길이','꽃받침폭']]
b=encoding[['품종_setosa','품종_versicolor','품종_virginica']]
print(a.shape,b.shape)

#모델 구조
X=tf.keras.layers.Input(shape=[4])
Y=tf.keras.layers.Dense(3,activation='softmax')(X)
model=tf.keras.models.Model(X,Y)
model.compile(loss='categorical_crossentropy',
              metrics='accuracy')

model.fit(a,b,epochs=1000)

print("predictions=",model.predict(a[-5:]))

print(b[-5:])

#학습한 가중치
model.get_weights()



