# -*- coding: utf-8 -*-
"""보스턴 집값 예측.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t5pMt4Dt5ePzTarHs3_pG3yUc2Yu31c8

##### 보스턴 집값 데이터: https://github.com/blackdew/tensorflow1/blob/master/csv/boston.csv
"""

import pandas as pd
import tensorflow as tf

boston_dir='https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
boston=pd.read_csv(boston_dir)
display(boston.head())
#medv(medium value): 중앙값

#a:독립변수(원인), b: 종속변수(결과)
a=boston[['crim','zn','indus','chas','nox','rm','age','dis','rad','tax','ptratio','b']]
b=boston[['lstat','medv']]
print(a.shape,b.shape)


X=tf.keras.layers.Input(shape=[12])
Y=tf.keras.layers.Dense(2)(X)
model=tf.keras.models.Model(X,Y)
model.compile(loss='mse')

model.fit(a,b,epochs=2000)

print("predictions:",model.predict(a[5:10]))

b[5:10]

#모델의 수식 확인
model.get_weights()

